set dotenv-load

namespace := "demo"
cluster_name := "demo"

default:
    @just --list --unsorted

# create demo cluster
create-cluster:
  k3d cluster create demo -p 8080:80

# load image and create namespace
prepare:
  k3d image import schwannden/demo-backend:0.1.0 -c {{cluster_name}}

# use helm to install
install:
  helm install demo-backend . --namespace demo --create-namespace

# use helm to upgrade an install
upgrade:
  helm upgrade demo-backend . --namespace demo

# use helm to uninstall
uninstall:
  helm uninstall demo-backend . --namespace demo
