set dotenv-load

script_dir := if os_family() == "windows" { "./backend" } else { "./backend" }

default:
    @just --list --unsorted

test:
  echo "version: $(poetry version -s)"

# build image
build:
  docker build . -f Dockerfile.prod -t "schwannden/demo-backend:$(poetry version -s)"

# publish image
publish:
  docker push "schwannden/k3d-demo-be:$(poetry version -s)"

# start minio server
start:
  docker compose up -d

# format python
format:
  autoflake --in-place --remove-all-unused-imports {{script_dir}} -r
  isort --profile black {{script_dir}}
  black {{script_dir}}

# stop minio server
stop:
  docker compose down

# restart minio server
restart: stop start
