set dotenv-load

namespace := "demo"
cluster_name := "demo"

default:
    @just --list --unsorted

# create demo cluster
create-cluster:
  k3d cluster create demo -p 8080:80

# load image and create namespace
prepare:
  k3d image import schwannden/demo-backend:0.1.0 -c {{cluster_name}}
  kubectl create namespace {{namespace}} --dry-run=client -o yaml | kubectl apply -f -

# use kubectl kustomize preview
preview env:
  kubectl kustomize overlays/{{env}}

# use kustomize to install
install env:
  kubectl apply -n {{namespace}} -k overlays/{{env}}

# use kustomize to uninstall
uninstall env:
  kubectl delete -n {{namespace}} -k overlays/{{env}}
