apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
        - name: demo-backend
          image: schwannden/demo-backend:0.1.0
          ports:
            - containerPort: 5000
          # env:
          #   - name: ENV
          #     value: prod
