set dotenv-load

namespace := "demo"
cluster_name := "demo"

default:
    @just --list --unsorted

# create demo cluster
create-cluster:
  k3d cluster create demo -p 8080:80

# load image and create namespace
prepare:
  k3d image import schwannden/demo-backend:0.1.0 -c {{cluster_name}}
  kubectl create namespace {{namespace}}

install:
  kubectl apply -f deployment.yaml -n {{namespace}}
  kubectl apply -f service.yaml -n {{namespace}}
  kubectl apply -f ingress.yaml -n {{namespace}}

# format python
uninstall:
  kubectl delete -f deployment.yaml -n {{namespace}}
  kubectl delete -f service.yaml -n {{namespace}}
  kubectl delete -f ingress.yaml -n {{namespace}}
