apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
spec:
  template:
    spec:
      containers:
        - name: demo-backend
          env:
            - name: ENV
              value: prod
